# Generated by Django 4.2.1 on 2023-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('detail', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
    ]
