# Generated by Django 4.0.4 on 2023-05-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexpense',
            old_name='amount',
            new_name='price',
        ),
    ]
