# Generated by Django 4.2.1 on 2023-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0003_dailyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='userId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyincome',
            name='userId',
            field=models.IntegerField(default=1),
        ),
    ]
