# Generated by Django 4.2.1 on 2023-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0004_dailyexpense_userid_dailyincome_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('budget', models.FloatField()),
                ('note', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='userId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
