# Generated by Django 4.2.1 on 2023-06-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0005_monthlybudget_alter_dailyexpense_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='note',
            field=models.TextField(),
        ),
    ]
