# Generated by Django 4.2.1 on 2023-06-21 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0006_monthlybudget_category_alter_monthlybudget_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
