# Generated by Django 4.2.1 on 2023-06-28 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0007_monthlybudget_created_at_monthlybudget_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyincome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyincome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
